provider: vault
docker: true
major-version: 5
makeTemplate: bridged
plugins:
  - name: gcp
    version: "5.26.0"
  - name: aws
    version: "5.42.0"
team: ecosystem
env:
  VAULT_DEV_ROOT_TOKEN_ID: "root"
javaGenVersion: "v0.9.5"
