provider: vault
docker: true
major-version: 6
makeTemplate: bridged
plugins:
  - name: std
    version: "1.6.2"

  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: gcp
    version: "5.26.0"
  - name: aws
    version: "5.42.0"
team: ecosystem
env:
  VAULT_DEV_ROOT_TOKEN_ID: "root"
actions:
  preTest:
    - name: Run provider tests
      run: |
        cd provider && go test -v -json -count=1 -cover -timeout 2h -tags=${{ matrix.language }} -parallel 4 . 2>&1 | tee /tmp/gotest.log | gotestfmt
pulumiConvert: 1
registryDocs: true
