provider: vault
docker: true
major-version: 7
makeTemplate: bridged
team: ecosystem
env:
    VAULT_DEV_ROOT_TOKEN_ID: "root"
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
