// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vault;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PasswordPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final PasswordPolicyArgs Empty = new PasswordPolicyArgs();

    /**
     * The name of the password policy.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the password policy.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * String containing a password policy.
     * 
     */
    @Import(name="policy", required=true)
    private Output<String> policy;

    /**
     * @return String containing a password policy.
     * 
     */
    public Output<String> policy() {
        return this.policy;
    }

    private PasswordPolicyArgs() {}

    private PasswordPolicyArgs(PasswordPolicyArgs $) {
        this.name = $.name;
        this.policy = $.policy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PasswordPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PasswordPolicyArgs $;

        public Builder() {
            $ = new PasswordPolicyArgs();
        }

        public Builder(PasswordPolicyArgs defaults) {
            $ = new PasswordPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the password policy.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the password policy.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param policy String containing a password policy.
         * 
         * @return builder
         * 
         */
        public Builder policy(Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy String containing a password policy.
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        public PasswordPolicyArgs build() {
            $.policy = Objects.requireNonNull($.policy, "expected parameter 'policy' to be non-null");
            return $;
        }
    }

}
