// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vault

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-vault/sdk/v7/go/vault/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages the CORS (Cross-Origin Resource Sharing) configuration for Vault, controlling which origins can make cross-origin requests and which headers are allowed.
//
// > **Important** This resource requires `sudo` capability and must be called from the root namespace. CORS configuration does not replicate across Performance Replication clusters in Vault Enterprise.
//
// **Note** This feature is available in Vault 1.14+
//
// ## Example Usage
//
// ### Enable CORS for specific origins
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-vault/sdk/v7/go/vault"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := vault.NewSysConfigCors(ctx, "example", &vault.SysConfigCorsArgs{
//				AllowedOrigins: pulumi.StringArray{
//					pulumi.String("http://www.example.com"),
//					pulumi.String("https://app.example.com"),
//				},
//				AllowedHeaders: pulumi.StringArray{
//					pulumi.String("X-Custom-Header"),
//					pulumi.String("X-Application-ID"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Allow all origins (wildcard)
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-vault/sdk/v7/go/vault"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := vault.NewSysConfigCors(ctx, "wildcard", &vault.SysConfigCorsArgs{
//				AllowedOrigins: pulumi.StringArray{
//					pulumi.String("*"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### Production environment configuration
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-vault/sdk/v7/go/vault"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := vault.NewSysConfigCors(ctx, "production", &vault.SysConfigCorsArgs{
//				AllowedOrigins: pulumi.StringArray{
//					pulumi.String("https://app.example.com"),
//					pulumi.String("https://admin.example.com"),
//					pulumi.String("https://api.example.com"),
//				},
//				AllowedHeaders: pulumi.StringArray{
//					pulumi.String("X-Custom-Header"),
//					pulumi.String("X-Request-ID"),
//					pulumi.String("X-Application-Version"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Security Considerations
//
// * The wildcard `"*"` origin should be used cautiously and typically only in development environments
// * Allowing all origins in production can expose Vault to cross-site request forgery attacks
// * Custom headers should be carefully reviewed to ensure they don't expose sensitive information
// * CORS settings must be configured from the root namespace
// * In Vault Enterprise with Performance Replication, CORS configuration does not replicate across clusters - each secondary cluster must have its CORS configuration set independently
// * To disable CORS, delete the resource using `terraform destroy` or remove it from your configuration. There is no `enabled = false` option
//
// ## API Documentation
//
// For more information on the Vault CORS configuration API, see the [Vault API documentation](https://developer.hashicorp.com/vault/api-docs/system/config-cors).
//
// ## Import
//
// CORS configuration can be imported using the fixed ID `sys/config/cors`:
//
// ```sh
// $ pulumi import vault:index/sysConfigCors:SysConfigCors example sys/config/cors
// ```
type SysConfigCors struct {
	pulumi.CustomResourceState

	// Set of additional custom headers allowed on cross-origin requests. Vault automatically includes standard headers, so only specify custom headers here. The standard headers that are always included are:
	// - `Content-Type`
	// - `X-Requested-With`
	// - `X-Vault-AWS-IAM-Server-ID`
	// - `X-Vault-MFA`
	// - `X-Vault-No-Request-Forwarding`
	// - `X-Vault-Wrap-Format`
	// - `X-Vault-Wrap-TTL`
	// - `X-Vault-Policy-Override`
	// - `Authorization`
	// - `X-Vault-Token`
	AllowedHeaders pulumi.StringArrayOutput `pulumi:"allowedHeaders"`
	// Set of origins permitted to make cross-origin requests. Use `"*"` as the only value to allow all origins. Must contain at least one origin.
	AllowedOrigins pulumi.StringArrayOutput `pulumi:"allowedOrigins"`
	// (Computed) Whether CORS is currently enabled. Vault automatically sets this to `true` when `allowedOrigins` is configured, and `false` when CORS is deleted.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
}

// NewSysConfigCors registers a new resource with the given unique name, arguments, and options.
func NewSysConfigCors(ctx *pulumi.Context,
	name string, args *SysConfigCorsArgs, opts ...pulumi.ResourceOption) (*SysConfigCors, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AllowedOrigins == nil {
		return nil, errors.New("invalid value for required argument 'AllowedOrigins'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SysConfigCors
	err := ctx.RegisterResource("vault:index/sysConfigCors:SysConfigCors", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSysConfigCors gets an existing SysConfigCors resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSysConfigCors(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SysConfigCorsState, opts ...pulumi.ResourceOption) (*SysConfigCors, error) {
	var resource SysConfigCors
	err := ctx.ReadResource("vault:index/sysConfigCors:SysConfigCors", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SysConfigCors resources.
type sysConfigCorsState struct {
	// Set of additional custom headers allowed on cross-origin requests. Vault automatically includes standard headers, so only specify custom headers here. The standard headers that are always included are:
	// - `Content-Type`
	// - `X-Requested-With`
	// - `X-Vault-AWS-IAM-Server-ID`
	// - `X-Vault-MFA`
	// - `X-Vault-No-Request-Forwarding`
	// - `X-Vault-Wrap-Format`
	// - `X-Vault-Wrap-TTL`
	// - `X-Vault-Policy-Override`
	// - `Authorization`
	// - `X-Vault-Token`
	AllowedHeaders []string `pulumi:"allowedHeaders"`
	// Set of origins permitted to make cross-origin requests. Use `"*"` as the only value to allow all origins. Must contain at least one origin.
	AllowedOrigins []string `pulumi:"allowedOrigins"`
	// (Computed) Whether CORS is currently enabled. Vault automatically sets this to `true` when `allowedOrigins` is configured, and `false` when CORS is deleted.
	Enabled *bool `pulumi:"enabled"`
}

type SysConfigCorsState struct {
	// Set of additional custom headers allowed on cross-origin requests. Vault automatically includes standard headers, so only specify custom headers here. The standard headers that are always included are:
	// - `Content-Type`
	// - `X-Requested-With`
	// - `X-Vault-AWS-IAM-Server-ID`
	// - `X-Vault-MFA`
	// - `X-Vault-No-Request-Forwarding`
	// - `X-Vault-Wrap-Format`
	// - `X-Vault-Wrap-TTL`
	// - `X-Vault-Policy-Override`
	// - `Authorization`
	// - `X-Vault-Token`
	AllowedHeaders pulumi.StringArrayInput
	// Set of origins permitted to make cross-origin requests. Use `"*"` as the only value to allow all origins. Must contain at least one origin.
	AllowedOrigins pulumi.StringArrayInput
	// (Computed) Whether CORS is currently enabled. Vault automatically sets this to `true` when `allowedOrigins` is configured, and `false` when CORS is deleted.
	Enabled pulumi.BoolPtrInput
}

func (SysConfigCorsState) ElementType() reflect.Type {
	return reflect.TypeOf((*sysConfigCorsState)(nil)).Elem()
}

type sysConfigCorsArgs struct {
	// Set of additional custom headers allowed on cross-origin requests. Vault automatically includes standard headers, so only specify custom headers here. The standard headers that are always included are:
	// - `Content-Type`
	// - `X-Requested-With`
	// - `X-Vault-AWS-IAM-Server-ID`
	// - `X-Vault-MFA`
	// - `X-Vault-No-Request-Forwarding`
	// - `X-Vault-Wrap-Format`
	// - `X-Vault-Wrap-TTL`
	// - `X-Vault-Policy-Override`
	// - `Authorization`
	// - `X-Vault-Token`
	AllowedHeaders []string `pulumi:"allowedHeaders"`
	// Set of origins permitted to make cross-origin requests. Use `"*"` as the only value to allow all origins. Must contain at least one origin.
	AllowedOrigins []string `pulumi:"allowedOrigins"`
}

// The set of arguments for constructing a SysConfigCors resource.
type SysConfigCorsArgs struct {
	// Set of additional custom headers allowed on cross-origin requests. Vault automatically includes standard headers, so only specify custom headers here. The standard headers that are always included are:
	// - `Content-Type`
	// - `X-Requested-With`
	// - `X-Vault-AWS-IAM-Server-ID`
	// - `X-Vault-MFA`
	// - `X-Vault-No-Request-Forwarding`
	// - `X-Vault-Wrap-Format`
	// - `X-Vault-Wrap-TTL`
	// - `X-Vault-Policy-Override`
	// - `Authorization`
	// - `X-Vault-Token`
	AllowedHeaders pulumi.StringArrayInput
	// Set of origins permitted to make cross-origin requests. Use `"*"` as the only value to allow all origins. Must contain at least one origin.
	AllowedOrigins pulumi.StringArrayInput
}

func (SysConfigCorsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*sysConfigCorsArgs)(nil)).Elem()
}

type SysConfigCorsInput interface {
	pulumi.Input

	ToSysConfigCorsOutput() SysConfigCorsOutput
	ToSysConfigCorsOutputWithContext(ctx context.Context) SysConfigCorsOutput
}

func (*SysConfigCors) ElementType() reflect.Type {
	return reflect.TypeOf((**SysConfigCors)(nil)).Elem()
}

func (i *SysConfigCors) ToSysConfigCorsOutput() SysConfigCorsOutput {
	return i.ToSysConfigCorsOutputWithContext(context.Background())
}

func (i *SysConfigCors) ToSysConfigCorsOutputWithContext(ctx context.Context) SysConfigCorsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SysConfigCorsOutput)
}

// SysConfigCorsArrayInput is an input type that accepts SysConfigCorsArray and SysConfigCorsArrayOutput values.
// You can construct a concrete instance of `SysConfigCorsArrayInput` via:
//
//	SysConfigCorsArray{ SysConfigCorsArgs{...} }
type SysConfigCorsArrayInput interface {
	pulumi.Input

	ToSysConfigCorsArrayOutput() SysConfigCorsArrayOutput
	ToSysConfigCorsArrayOutputWithContext(context.Context) SysConfigCorsArrayOutput
}

type SysConfigCorsArray []SysConfigCorsInput

func (SysConfigCorsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SysConfigCors)(nil)).Elem()
}

func (i SysConfigCorsArray) ToSysConfigCorsArrayOutput() SysConfigCorsArrayOutput {
	return i.ToSysConfigCorsArrayOutputWithContext(context.Background())
}

func (i SysConfigCorsArray) ToSysConfigCorsArrayOutputWithContext(ctx context.Context) SysConfigCorsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SysConfigCorsArrayOutput)
}

// SysConfigCorsMapInput is an input type that accepts SysConfigCorsMap and SysConfigCorsMapOutput values.
// You can construct a concrete instance of `SysConfigCorsMapInput` via:
//
//	SysConfigCorsMap{ "key": SysConfigCorsArgs{...} }
type SysConfigCorsMapInput interface {
	pulumi.Input

	ToSysConfigCorsMapOutput() SysConfigCorsMapOutput
	ToSysConfigCorsMapOutputWithContext(context.Context) SysConfigCorsMapOutput
}

type SysConfigCorsMap map[string]SysConfigCorsInput

func (SysConfigCorsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SysConfigCors)(nil)).Elem()
}

func (i SysConfigCorsMap) ToSysConfigCorsMapOutput() SysConfigCorsMapOutput {
	return i.ToSysConfigCorsMapOutputWithContext(context.Background())
}

func (i SysConfigCorsMap) ToSysConfigCorsMapOutputWithContext(ctx context.Context) SysConfigCorsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SysConfigCorsMapOutput)
}

type SysConfigCorsOutput struct{ *pulumi.OutputState }

func (SysConfigCorsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SysConfigCors)(nil)).Elem()
}

func (o SysConfigCorsOutput) ToSysConfigCorsOutput() SysConfigCorsOutput {
	return o
}

func (o SysConfigCorsOutput) ToSysConfigCorsOutputWithContext(ctx context.Context) SysConfigCorsOutput {
	return o
}

// Set of additional custom headers allowed on cross-origin requests. Vault automatically includes standard headers, so only specify custom headers here. The standard headers that are always included are:
// - `Content-Type`
// - `X-Requested-With`
// - `X-Vault-AWS-IAM-Server-ID`
// - `X-Vault-MFA`
// - `X-Vault-No-Request-Forwarding`
// - `X-Vault-Wrap-Format`
// - `X-Vault-Wrap-TTL`
// - `X-Vault-Policy-Override`
// - `Authorization`
// - `X-Vault-Token`
func (o SysConfigCorsOutput) AllowedHeaders() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SysConfigCors) pulumi.StringArrayOutput { return v.AllowedHeaders }).(pulumi.StringArrayOutput)
}

// Set of origins permitted to make cross-origin requests. Use `"*"` as the only value to allow all origins. Must contain at least one origin.
func (o SysConfigCorsOutput) AllowedOrigins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SysConfigCors) pulumi.StringArrayOutput { return v.AllowedOrigins }).(pulumi.StringArrayOutput)
}

// (Computed) Whether CORS is currently enabled. Vault automatically sets this to `true` when `allowedOrigins` is configured, and `false` when CORS is deleted.
func (o SysConfigCorsOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *SysConfigCors) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

type SysConfigCorsArrayOutput struct{ *pulumi.OutputState }

func (SysConfigCorsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SysConfigCors)(nil)).Elem()
}

func (o SysConfigCorsArrayOutput) ToSysConfigCorsArrayOutput() SysConfigCorsArrayOutput {
	return o
}

func (o SysConfigCorsArrayOutput) ToSysConfigCorsArrayOutputWithContext(ctx context.Context) SysConfigCorsArrayOutput {
	return o
}

func (o SysConfigCorsArrayOutput) Index(i pulumi.IntInput) SysConfigCorsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SysConfigCors {
		return vs[0].([]*SysConfigCors)[vs[1].(int)]
	}).(SysConfigCorsOutput)
}

type SysConfigCorsMapOutput struct{ *pulumi.OutputState }

func (SysConfigCorsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SysConfigCors)(nil)).Elem()
}

func (o SysConfigCorsMapOutput) ToSysConfigCorsMapOutput() SysConfigCorsMapOutput {
	return o
}

func (o SysConfigCorsMapOutput) ToSysConfigCorsMapOutputWithContext(ctx context.Context) SysConfigCorsMapOutput {
	return o
}

func (o SysConfigCorsMapOutput) MapIndex(k pulumi.StringInput) SysConfigCorsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SysConfigCors {
		return vs[0].(map[string]*SysConfigCors)[vs[1].(string)]
	}).(SysConfigCorsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SysConfigCorsInput)(nil)).Elem(), &SysConfigCors{})
	pulumi.RegisterInputType(reflect.TypeOf((*SysConfigCorsArrayInput)(nil)).Elem(), SysConfigCorsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SysConfigCorsMapInput)(nil)).Elem(), SysConfigCorsMap{})
	pulumi.RegisterOutputType(SysConfigCorsOutput{})
	pulumi.RegisterOutputType(SysConfigCorsArrayOutput{})
	pulumi.RegisterOutputType(SysConfigCorsMapOutput{})
}
