// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Provides a resource to manage [Namespaces](https://www.vaultproject.io/docs/enterprise/namespaces/index.html).
 *
 * **Note** this feature is available only with Vault Enterprise.
 *
 * ## Example Usage
 *
 * ### Single namespace
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vault from "@pulumi/vault";
 *
 * const ns1 = new vault.Namespace("ns1", {path: "ns1"});
 * ```
 *
 * ### Nested namespaces
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vault from "@pulumi/vault";
 *
 * const config = new pulumi.Config();
 * const childNamespaces = config.getObject<Array<string>>("childNamespaces") || [
 *     "child_0",
 *     "child_1",
 *     "child_2",
 * ];
 * const parent = new vault.Namespace("parent", {path: "parent"});
 * const children: vault.Namespace[] = [];
 * for (const range of childNamespaces.map((v, k) => ({key: k, value: v}))) {
 *     children.push(new vault.Namespace(`children-${range.key}`, {
 *         namespace: parent.path,
 *         path: range.key,
 *     }));
 * }
 * const childrenMount: vault.Mount[] = [];
 * children.apply(rangeBody => {
 *     for (const range of rangeBody.map((v, k) => ({key: k, value: v}))) {
 *         childrenMount.push(new vault.Mount(`children-${range.key}`, {
 *             namespace: range.value.pathFq,
 *             path: "secrets",
 *             type: "kv",
 *             options: {
 *                 version: "1",
 *             },
 *         }));
 *     }
 * });
 * const childrenSecret: vault.generic.Secret[] = [];
 * childrenMount.apply(rangeBody => {
 *     for (const range of rangeBody.map((v, k) => ({key: k, value: v}))) {
 *         childrenSecret.push(new vault.generic.Secret(`children-${range.key}`, {
 *             namespace: range.value.namespace,
 *             path: `${range.value.path}/secret`,
 *             dataJson: JSON.stringify({
 *                 ns: range.key,
 *             }),
 *         }));
 *     }
 * });
 * ```
 *
 * ## Tutorials
 *
 * Refer to the [Codify Management of Vault Enterprise Using Terraform](https://learn.hashicorp.com/tutorials/vault/codify-mgmt-enterprise) tutorial for additional examples using Vault namespaces.
 *
 * ## Import
 *
 * Namespaces can be imported using its `name` as accessor id
 *
 * ```sh
 * $ pulumi import vault:index/namespace:Namespace example <name>
 * ```
 *
 * If the declared resource is imported and intends to support namespaces using a provider alias, then the name is relative to the namespace path.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vault from "@pulumi/vault";
 *
 * const example2 = new vault.Namespace("example2", {path: "example2"});
 * ```
 *
 * ```sh
 * $ pulumi import vault:index/namespace:Namespace example2 example2
 *
 * $ terraform state show vault_namespace.example2
 * ```
 *
 * vault_namespace.example2:
 * resource "vault.Namespace" "example2" {
 * id           = "example/example2/"
 * namespaceId = <known after import>
 * path         = "example2"
 * pathFq      = "example2"
 * }
 */
export class Namespace extends pulumi.CustomResource {
    /**
     * Get an existing Namespace resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NamespaceState, opts?: pulumi.CustomResourceOptions): Namespace {
        return new Namespace(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vault:index/namespace:Namespace';

    /**
     * Returns true if the given object is an instance of Namespace.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Namespace {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Namespace.__pulumiType;
    }

    /**
     * Custom metadata describing this namespace. Value type
     * is `map[string]string`. Requires Vault version 1.12+.
     */
    declare public readonly customMetadata: pulumi.Output<{[key: string]: string}>;
    /**
     * The namespace to provision the resource in.
     * The value should not contain leading or trailing forward slashes.
     * The `namespace` is always relative to the provider's configured [namespace](https://www.terraform.io/docs/providers/vault/index.html#namespace).
     * *Available only for Vault Enterprise*.
     */
    declare public readonly namespace: pulumi.Output<string | undefined>;
    /**
     * Vault server's internal ID of the namespace.
     */
    declare public /*out*/ readonly namespaceId: pulumi.Output<string>;
    /**
     * The path of the namespace. Must not have a trailing `/`.
     */
    declare public readonly path: pulumi.Output<string>;
    /**
     * The fully qualified path to the namespace. Useful when provisioning resources in a child `namespace`.
     * The path is relative to the provider's `namespace` argument.
     */
    declare public readonly pathFq: pulumi.Output<string>;

    /**
     * Create a Namespace resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NamespaceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NamespaceArgs | NamespaceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NamespaceState | undefined;
            resourceInputs["customMetadata"] = state?.customMetadata;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["namespaceId"] = state?.namespaceId;
            resourceInputs["path"] = state?.path;
            resourceInputs["pathFq"] = state?.pathFq;
        } else {
            const args = argsOrState as NamespaceArgs | undefined;
            if (args?.path === undefined && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            resourceInputs["customMetadata"] = args?.customMetadata;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["path"] = args?.path;
            resourceInputs["pathFq"] = args?.pathFq;
            resourceInputs["namespaceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Namespace.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Namespace resources.
 */
export interface NamespaceState {
    /**
     * Custom metadata describing this namespace. Value type
     * is `map[string]string`. Requires Vault version 1.12+.
     */
    customMetadata?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The namespace to provision the resource in.
     * The value should not contain leading or trailing forward slashes.
     * The `namespace` is always relative to the provider's configured [namespace](https://www.terraform.io/docs/providers/vault/index.html#namespace).
     * *Available only for Vault Enterprise*.
     */
    namespace?: pulumi.Input<string>;
    /**
     * Vault server's internal ID of the namespace.
     */
    namespaceId?: pulumi.Input<string>;
    /**
     * The path of the namespace. Must not have a trailing `/`.
     */
    path?: pulumi.Input<string>;
    /**
     * The fully qualified path to the namespace. Useful when provisioning resources in a child `namespace`.
     * The path is relative to the provider's `namespace` argument.
     */
    pathFq?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Namespace resource.
 */
export interface NamespaceArgs {
    /**
     * Custom metadata describing this namespace. Value type
     * is `map[string]string`. Requires Vault version 1.12+.
     */
    customMetadata?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The namespace to provision the resource in.
     * The value should not contain leading or trailing forward slashes.
     * The `namespace` is always relative to the provider's configured [namespace](https://www.terraform.io/docs/providers/vault/index.html#namespace).
     * *Available only for Vault Enterprise*.
     */
    namespace?: pulumi.Input<string>;
    /**
     * The path of the namespace. Must not have a trailing `/`.
     */
    path: pulumi.Input<string>;
    /**
     * The fully qualified path to the namespace. Useful when provisioning resources in a child `namespace`.
     * The path is relative to the provider's `namespace` argument.
     */
    pathFq?: pulumi.Input<string>;
}
